##version: '3.8'

services:
  app:
    image: authuser-app:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
