version: '3.8'

services:
  app:
    image: authuser-app:latest
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do host para a porta 8080 do container
    environment:
      SPRING_PROFILES_ACTIVE: production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
