apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-projeto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-projeto
  template:
    metadata:
      labels:
        app: meu-projeto
    spec:
      containers:
      - name: meu-projeto
        image: meu-projeto:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: meu-projeto-service
spec:
  selector:
    app: meu-projeto
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
