name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./authuser/authuser

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Seu nome de usuário do Docker Hub
          password: ${{ secrets.DOCKER_HUB_TOKEN }}      # O token que você acabou de adicionar


      - name: List files in authuser/authuser directory
        run: ls -l ./authuser/authuser

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment"
          docker-compose -f ./docker-compose.staging.yml up -d --build
          docker-compose -f ./docker-compose.staging.yml ps

      - name: Check Staging Deployment
        run: |
          docker-compose -f ./docker-compose.staging.yml ps
          if [ $? -ne 0 ]; then
            echo "Deployment failed!"
            exit 1
          fi

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: List files in authuser/authuser directory
        run: ls -l ./authuser/authuser

      - name: Deploy to Production
        run: |
          echo "Deploying to Production Environment"
          docker-compose -f ./docker-compose.production.yml up -d --build
          docker-compose -f ./docker-compose.production.yml ps

      - name: Check Production Deployment
        run: |
          docker-compose -f ./docker-compose.production.yml ps
          if [ $? -ne 0 ]; then
            echo "Deployment failed!"
            exit 1
          fi
