name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Navigate to authuser directory
        run: cd ./authuser  # Navegar até o diretório onde está o pom.xml

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./authuser  # Define o diretório de trabalho para o comando Maven

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment"
          docker-compose -f ./docker-compose.staging.yml up -d --build
        working-directory: ./authuser  # Define o diretório de trabalho para o comando Docker

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Deploy to Production
        run: |
          echo "Deploying to Production Environment"
          docker-compose -f ./docker-compose.production.yml up -d --build
        working-directory: ./authuser  # Define o diretório de trabalho para o comando Docker
