name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # 'adopt' foi substituído pelo 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./authuser/authuser
#
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Deploy to Production
        run: |
          echo "Deploying to Production Environment"
          docker-compose -f ./docker-compose.yml up -d --build
          docker-compose -f ./docker-compose.yml ps

      - name: Check Production Deployment
        run: |
          docker-compose -f ./docker-compose.yml ps
          if [ $? -ne 0 ]; then
            echo "Deployment failed!"
            exit 1
          fi
